/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'gstarke' at '22.02.16 21:54' with Gradle 2.11
 *
 * @author gstarke, @date 22.02.16 21:54
 */
import static groovy.io.FileType.FILES

class LeanMarkdownToc {

    static final String BOOK_DIR = "/Users/gstarke/Dropbox/arc42inpractice"

    static final String MANUSCRIPT_DIR = "${BOOK_DIR}/manuscript"

    static final String TABLE_OF_DIR = "${MANUSCRIPT_DIR}/99_generated_tables"

    static final String TO_TIPS_FILENAME =
            "$TABLE_OF_DIR/generated-table-of-tips.md"

    static final String TIPS_INDICATOR = "#### Tip"

    static final String TO_QUESTIONS_FILENAME =
            "$TABLE_OF_DIR/generated-table-of-questions.md"

    static final String MARKDOWN_EXTENSION = ".md"

    static final nrOfTips = 0

    static void traverseMarkdownFiles(File contentDir) {
        contentDir.eachFileRecurse(FILES) { currentFile ->
            if (currentFile.name.endsWith('.md')) {
                traverseFile(currentFile)
            }
        }
    }

    static void traverseFile(File currentFile) {
        println "processing $currentFile"
        currentFile.eachLine { currentLine ->
            if (currentLine =~ /#### Tip*/) {
                processTip(currentLine)
            }
            //else if (currentLine =~ /### Tip/ )
        }
    }

    private static processTip(String currentLine) {
        println currentLine
    }

    static void main(String[] args) {
        def dir = new File(MANUSCRIPT_DIR)

        traverseMarkdownFiles(dir)
    }
}
