/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'gstarke' at '22.02.16 21:54' with Gradle 2.11
 *
 * @author gstarke, @date 22.02.16 21:54
 */
import static groovy.io.FileType.FILES

class LeanMarkdownToc {

    static final String BOOK_DIR = "/Users/gstarke/projects/arc42-in-practice"

    static final String MANUSCRIPT_DIR = "${BOOK_DIR}/manuscript"

    static final String TABLE_OF_DIR = "${MANUSCRIPT_DIR}/99_generated_tables"

    static final String TO_TIPS_FILENAME =
            "$TABLE_OF_DIR/generated-table-of-tips.md"

    static final String TIPS_MATCHER = /^#### Tip*/
    static final String WRONG_TIPS_MATCHER = /^#{1,3} Tip/

    static final String QUESTION_FORMAT = /#### Question*/

    static final String TO_QUESTIONS_FILENAME =
            "$TABLE_OF_DIR/generated-table-of-questions.md"

    static final String MARKDOWN_EXTENSION = ".md"

    static int nrOfTips = 0
    static int nrOfQuestions = 0

    static ArrayList<?> tips
    static ArrayList<String> questions

    static void traverseMarkdownFiles(File contentDir) {
        contentDir.eachFileRecurse(FILES) { currentFile ->
            if (currentFile.name.endsWith('.md')) {
                traverseFile(currentFile)
            }
        }
    }

    static void traverseFile(File currentFile) {
        println "processing $currentFile"
        currentFile.eachLine { currentLine ->
            processLine( currentLine, currentFile )
        }

    }

    static void processLine( String currentLine, File currentFile) {
        checkTip( currentLine, currentFile )
        checkQuestion( currentLine, currentFile)
    }


    // 1.) include tips into table-of-tips,
    // 2.) issue warning if tip is wrongly formated
    static void checkTip( String currentLine, File currentFile ) {
        if (currentLine =~ TIPS_MATCHER ) {
            includeTipInTableOfTips( currentLine )
        }
    }


    private static includeTipInTableOfTips( String currentLine) {
        tips.add( currentLine )
        nrOfTips++
    }


    // 1.) include question into table-of-questions,
    // 2.) issue warning if question is wrongly formated
    static void checkQuestion( String currentLine, File currentFile ) {
        if (currentLine =~ /#### Question*/) {
            includeQuestionInTableOfQuestions( currentLine )
        }
    }
    private static includeQuestionInTableOfQuestions( String currentLine ) {
        println currentLine
    }

    static boolean isCorrectTip( String line ) {
        return (line =~ TIPS_MATCHER)
    }

    static void main(String[] args) {
        def dir = new File(MANUSCRIPT_DIR)

        tips = new ArrayList<String>()

        traverseMarkdownFiles(dir)

        println "Found $nrOfTips tips:"
        println tips
    }
}
