/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'gstarke' at '22.02.16 21:54' with Gradle 2.11
 *
 * @author gstarke, @date 22.02.16 21:54
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        LeanMarkdownToc lib = new LeanMarkdownToc()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
