/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'gstarke' at '22.02.16 21:54' with Gradle 2.11
 *
 * @author gstarke, @date 22.02.16 21:54
 */

import spock.lang.Specification
import spock.lang.Unroll

class MarkdownFinderSpec extends Specification {
    public void setup() {

    }


    @Unroll
    def "find tips in markdown"() {
        expect:
        LeanMarkdownToc.isCorrectTip( line ) == isCorrectTipFormat
        // assertEquals( (line =~ LeanMarkdownToc.TIPS_MATCHER), isCorrectTipFormat )

        where:

        isCorrectTipFormat | line
        false              | "# Tip I-14: Hold your breath"
        false              | "## Tip II-14: Hold your breath"
        false              | "### Tip III-14: Hold your breath"
        true               | "#### Tip IV-14: Hold your breath"
        true               | "#### Tip IV-3:"
        false              | "###### Tip VI-9: Too deeply nested"

    }

}